import { FC } from "react";
import Head from 'next/head'
import { Navbar } from '../Navbar'
import style from './MainLayout.module.css'

interface MainLayoutProps {
  children: React.ReactNode;
}

export const MainLayout:FC<MainLayoutProps>  = ({children}) => {
  return (
    <div className={style.container}>
      <Head>
        <title>Create Next App jr </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={style.main}>
        {children}
      </main>
    </div>
  )
}
